[workspace]
resolver = "3"
members = ["crates/core", "crates/ui", "crates/app"]

[workspace.package]
edition = "2024"
version = "0.1.2" # x-release-please-version
license = "MIT"
repository = "https://github.com/SpechtLabs/telegram-tui"

[workspace.dependencies]
tgt-core = { path = "crates/core" }
tgt-ui = { path = "crates/ui" }
tokio = "=1.53.1"
async-trait = "=0.1.91"
thiserror = "=2.0.19"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
tracing = "=0.1.44"
insta = { version = "=1.48.0", features = ["json"] }

[profile.release]
lto = "thin"
strip = "debuginfo"
