#!/usr/bin/env bash
# Emit the Homebrew formula for a published release to stdout.
#
#   scripts/brew-formula.sh <version> <checksum-dir>
#
# <checksum-dir> holds one `<target>.sha256` per published target, exactly as
# the release workflow's build matrix uploads them.
#
# A *formula*, not a cask, even though SpechtLabs/homebrew-tap is otherwise
# casks: Homebrew on Linux does not support casks at all, and this project
# publishes Linux artifacts. A formula is also the only one of the two that can
# run an `install` method, which the bin/ + lib/ layout needs.
set -euo pipefail

version="${1:?usage: brew-formula.sh <version> <checksum-dir>}"
checksum_dir="${2:?usage: brew-formula.sh <version> <checksum-dir>}"

repo="SpechtLabs/telegram-tui"
base_url="https://github.com/$repo/releases/download/v$version"

sha_for() {
    local target="$1"
    local file="$checksum_dir/$target.sha256"
    if [[ ! -f "$file" ]]; then
        echo "error: no checksum for $target (expected $file)" >&2
        return 1
    fi
    local sha
    sha="$(awk 'NR == 1 { print $1 }' "$file")"
    if [[ ! "$sha" =~ ^[0-9a-f]{64}$ ]]; then
        echo "error: '$sha' in $file is not a sha256" >&2
        return 1
    fi
    printf '%s' "$sha"
}

# Plain assignments, deliberately not `local`/`declare`: those mask the exit
# status of the command substitution and would paper over a missing checksum.
sha_macos_arm="$(sha_for aarch64-apple-darwin)"
sha_macos_intel="$(sha_for x86_64-apple-darwin)"
sha_linux_arm="$(sha_for aarch64-unknown-linux-gnu)"
sha_linux_intel="$(sha_for x86_64-unknown-linux-gnu)"

cat <<FORMULA
# This file is generated by the telegram-tui release workflow. DO NOT EDIT.
class Tgt < Formula
  desc "Keyboard-driven Telegram client for the terminal"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  # Ordered to satisfy brew style's FormulaAudit/ComponentsOrder: livecheck
  # comes before the on_<os> blocks.
  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    if Hardware::CPU.arm?
      url "$base_url/tgt-$version-aarch64-apple-darwin.tar.gz"
      sha256 "$sha_macos_arm"
    end
    if Hardware::CPU.intel?
      url "$base_url/tgt-$version-x86_64-apple-darwin.tar.gz"
      sha256 "$sha_macos_intel"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$base_url/tgt-$version-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_arm"
    end
    if Hardware::CPU.intel?
      url "$base_url/tgt-$version-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_intel"
    end
  end

  # The tarball is a relocatable bin/ + lib/ pair: tgt loads TDLib through a
  # runpath the loader expands relative to the executable itself
  # (\`@executable_path/../lib\` on macOS, \`\$ORIGIN/../lib\` on Linux), so the two
  # directories have to stay siblings. Keeping them under libexec is what makes
  # that safe here — libexec is the one prefix directory Homebrew does not link
  # into HOMEBREW_PREFIX, so libtdjson (and the C++ runtime bundled beside it on
  # Linux) never lands in the shared lib/. Both dyld and glibc's ld.so resolve
  # the symlink to its real path before expanding the runpath, so the linked
  # bin/tgt still finds libexec/lib.
  # Homebrew strips a single top-level directory when it stages an archive, so
  # by the time this runs the working directory already *is* the contents of
  # the tarball's tgt/ — globbing "tgt/*" matches nothing, and v0.1.4 installed
  # an empty libexec and a dangling bin symlink because of it. The dotfile glob
  # is separate because Ruby's Dir["*"] skips dotfiles, which would silently
  # drop the .tgt-install marker that \`tgt update\` reads to confirm a tree is
  # ours. Dir returns [] when it matches nothing, so this stays correct for
  # releases predating the marker.
  def install
    libexec.install Dir["*"] + Dir[".tgt-install"]
    bin.install_symlink libexec/"bin/tgt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tgt --version")
  end
end
FORMULA
